### ISSUE TITLE
parse.py

### ISSUE THREAD

**Issue by JessyD** [pgleeson/rate#1]
Hi,

@pgleeson  I tried to run `parse.py -jnmlnrn` but it seems that `delay is not an attribute` and the code fails. 

The error is:
```
Id iclamp_0 not found in <neuroml> element. All ids: ['TestNetwork']
Traceback (most recent call last):
  File "parse.py", line 137, in <module>
    check_to_generate_or_run(sys.argv, sim)
  File "build/bdist.macosx-10.12-x86_64/egg/neuromllite/NetworkGenerator.py", line 202, in check_to_generate_or_run
  File "build/bdist.macosx-10.12-x86_64/egg/neuromllite/NetworkGenerator.py", line 678, in generate_and_run
  File "build/bdist.macosx-10.12-x86_64/egg/neuromllite/NetworkGenerator.py", line 261, in generate_neuroml2_from_network
  File "<string>", line 1, in <module>
AttributeError: 'builtin_function_or_method' object has no attribute 'delay'
```

Is there a more recent version of the code where `delay` is an allowed field?

**Comment by pgleeson** [comment]
Looks like you have anout of date version of nmllite. See https://github.com/NeuroML/NeuroMLlite/blob/master/neuromllite/__init__.py#L68, neuroml2_input is present there. Get the latest version, revert your changes and it should work.

**Comment by JessyD** [comment]
Sorry, I had noticed that, fixed the error and edited the issue with the new error I get after getting the latest version of NeuroMLlite. Sorry for the confusion. The `delay` specification is now throwing an error.

Also, just to make sure on the NeuromLlite repo is the `Example3.py` the only one where the simulation is currently working?

**Comment by pgleeson** [comment]
Looks like it's something related to neuroml2_input.. did you revert the parse.py file? Try a fresh check out and maybbe check for latest libneuroml also.
